<a href="https://colab.research.google.com/github/sturu1/github-first/blob/master/2020_07_09_%EC%98%A4%ED%9B%84%EC%88%98%EC%97%85_%EC%A0%95%EC%84%9D%EB%B4%89%EC%88%98%EC%97%85_6%EC%A3%BC_3_5_%EB%8B%A4%EC%8B%9C%ED%99%95%EC%9D%B8%ED%95%A0%EA%B2%83_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from keras.datasets import imdb

Using TensorFlow backend.


In [5]:
(train_data, train_labels), (test_data, tst_labelss) = imdb.load_data(num_words=10000)

17465344/17464789 [==============================] - 1s 0us/step


In [ ]:
train_data[0]

In [7]:
train_labels[0]

1

In [12]:
word_index = imdb.get_word_index()

In [39]:
reverse_word_index = dict([(value, key) for key, value in word_index.items()])

In [41]:
' '.join([reverse_word_index.get(i-3, '?') for i in train_data[0]])

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [19]:
import numpy as np

In [20]:
def vectorize_sequences(seqeunces, dimension = 10000):
  results = np.zeros((len(seqeunces), dimension))
  for i, seqeunce in enumerate(seqeunces):
    results[i, seqeunce] = 1.
  return results

In [21]:
x_train = vectorize_sequences(train_data)

In [22]:
x_test = vectorize_sequences(test_data)

In [23]:
x_train[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [24]:
y_train = np.array(train_labels, dtype = np.float32)

In [42]:
y_test = np.array(test_labels, dtype = np.float32)

NameError: ignored

In [26]:
y_train

array([1., 0., 0., ..., 0., 1., 0.], dtype=float32)

In [27]:
from keras import models

In [28]:
from keras import layers

In [29]:
model = models.Sequential()

In [30]:
model.add(layers.Dense(units=16, activation='relu', input_shape=(10000, )))

In [31]:
model.add(layers.Dense(units=16, activation='relu'))

In [32]:
model.add(layers.Dense(units=1, activation='sigmoid',))

In [33]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [34]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                160016    
_________________________________________________________________
dense_2 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17        
Total params: 160,305
Trainable params: 160,305
Non-trainable params: 0
_________________________________________________________________


In [46]:
x_val = (:10000)
y_val = (:10000)

SyntaxError: ignored

In [ ]:
history = model.fit(partial_x_train, partial_y_train,
                   wpochs=20, batch_size=512,
                   validation_data=(x_val, y_val))

In [ ]:
history.history.keys()

In [48]:
import matplotlib.pyplot as plt

acc=history.history['accracy']
val_acc=history.history['val_accracy']
loss=history.history['loss']
val_loss=history.history['val_loss']

NameError: ignored

In [50]:
epochs = range(1, len(acc)+1)

NameError: ignored

In [ ]:
plt.plot(epochs, loss, 'bo', label='Tranining loss')
plt.plot(epochs, val_loss, 'b', label='validation loss')
plt.title('Tranining and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

In [51]:
acc=history.history['accracy']
val_acc=history.history['val_accracy']

plt.plot(epochs, acc, 'bo', label='Tranining acc')
plt.plot(epochs, val_acc, 'b', label='validation acc')
plt.title('Tranining and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

NameError: ignored

In [52]:
model = models.Sequential()
model.add(layers.Dense(units=16, activation='relu', input_shape=(10000, )))
model.add(layers.Dense(units=16, activation='relu'))
model.add(layers.Dense(units=1, activation='sigmoid',))

In [53]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [60]:
model.fit(x_train, y_train, epochs=4, batch_size=512)

Epoch 1/4
25000/25000 [==============================] - 1s 44us/step - loss: 0.1397 - accuracy: 0.9504
Epoch 2/4
25000/25000 [==============================] - 1s 43us/step - loss: 0.1236 - accuracy: 0.9558
Epoch 3/4
25000/25000 [==============================] - 1s 44us/step - loss: 0.1099 - accuracy: 0.9628
Epoch 4/4
25000/25000 [==============================] - 1s 44us/step - loss: 0.0971 - accuracy: 0.9670


In [61]:
results = model.evaluate(x_test, y_test)

NameError: ignored

In [62]:
results

NameError: ignored

In [63]:
model.predict(x_test)

array([[0.11968982],
       [0.99996006],
       [0.8619395 ],
       ...,
       [0.13839674],
       [0.02574688],
       [0.7103376 ]], dtype=float32)

In [64]:
model.predict_classes(x_test)

array([[0],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]], dtype=int32)